### ISSUE TITLE
[제안] 언어별로 별도의 프로젝트를 만드는 것이 좋겠습니다.

### ISSUE THREAD

**Issue by gongdo** [iamport/iamport-rest-client#1]
각 언어는 그 언어에 맞는 컨벤션도 있고 코드 개발의 라이프사이클이 다릅니다.
폴더로 구분하기보다는 언어별로 별도의 프로젝트를 만드는 것이 좋다고 생각합니다.

예를 들어 php라면 `iamport-rest-client-php`, python이라면 `iamport-rest-client-python`이 되겠지요.

아직 버저닝등의 이슈는 나오지 않았지만 각 언어별 버전 관리도 별도의 프로젝트로 관리하는 것이 좋겠습니다.

어떻게 생각하시는지요?

**Comment by jangbora** [comment]
그 방법이 체크아웃 받아서 사용하는 사용자들에게도 훨씬 더 편리할 것 같습니다. 
말씀하신 방법이 버저닝이나 fork등 여러 면에서 좋을 것 같습니다. 

repository개설을 누가 할 것인가에 대한 고민이 생기는데요
최초 커미터가 개설을 해주시는 것이 보다 정당하지 않을까 싶은데 이 부분은 어떻게 생각하시는지요?
(가령, nodejs를 제가 리드할 것이 아닌데 제가 repository를 개설하고 커미터를 받는 것은 좀 정당해보이지 않아서요)

**Comment by gongdo** [comment]
각자 개별 리포지토리를 만들고 이것을 메인 호스트가 fork하는 사례도 없지 않지만 일단 리포지토리 자체는 iamport가 관리하는게 혼선이 적을거란 생각이 듭니다.
아직 해보진 않았지만 settings에 보면 `Transfer ownership`이 있습니다. 이걸 이용해서 먼저 커미터가 '섭외'가 된 언어별로 빈 리포지토리를 만들고 마스터 커미터에게 오너십을 넘겨주는 방법은 어떨까요?
**수정**
지금 보니 이건 오너십을 넘긴쪽으로 리포지토리가 아예 이전이 되는거네요.
다른 방안을 한 번 찾아보긴 하겠습니다만 제 의견은 오너십은 iamport가 갖고 co-contributor중 하나를 메인 커미터로 지정하는게 좋을 것 같습니다.

**수정2**
http://stackoverflow.com/questions/8015579/add-another-user-to-project-owners-in-github
이 글에 의하면 Organization을 하나 만들면 거기에는 co-owner를 지정할 수 있는 것 같습니다.
이게 권한이 어느정도로 관리되는지는 모르겠지만 이쪽도 한 번 검토해보시는건 어떨까요?

**수정3**
물론 제가 제안한 방법은 모두 iamport라는 organization에 외부 개발자가 포함이 되는 뉘앙스라서 좋지 않을 수도 있을 것 같습니다.
우선은 커미터 각자가 개별 repository를 만들고 iamport는 이것을 링크 걸어주는 `Home`리포지토리 같은걸로 관리해도 될 것 같습니다.

**Comment by gongdo** [comment]
오래된 이슈라서 닫습니다.
