### ISSUE TITLE
[문의] 사용할 수 있는 결제사/결제수단 상수값

### ISSUE THREAD

**Issue by gongdo** [iamport/iamport-rest-client#4]
샘플 코드, 문서, 깃헙 문서 등으로 흩어져 있는데 다음과 같이 한 곳에 정리가 되었으면 합니다.
https://github.com/OpenBapul/iamport-rest-client-net/wiki/PaymentGateway

여기에서 제가 알기 어려운 것은 각 상수값이 import.payment.js 버전에 따라 다르게 적용되는지 여부입니다. 물론 대부분의 경우 최신 버전을 쓰겠지만 그래도 버전, 날짜, 지원되는 상수값이 정리되어 있는게 좋겠습니다.

**Comment by jangbora** [comment]
param 속성 자체의 지원여부는 iamport.payment.js의 버전에 따라 차이가 있습니다만, 
속성 하나가 특정 버전에서 지원되기 시작하면 속성의 값은 버전을 타지 않아 별도로 명기하지 못했습니다. 
예시로, pg라는 속성 자체는 1.1.0부터 지원이 되지만 pg속성이 가질 수 있는 값은 1.1.0 / 1.1.1 / 1.1.2 모두 동일합니다.(inicis, html5_inicis, kakao, 등등 모두 동일하게 사용가능)

느리게...현재 진행형이라 혼란을 드리고 있습니다. ㅠ 최종적으로 모든 샘플과 문서를 깃헙으로 이전하려는 계획에 있습니다.

**Comment by gongdo** [comment]
오래된 이슈라서 닫습니다.
